import os
from os.path import abspath

srcdir = "."
blddir = "build"

def set_options(opt):
	opt.tool_options('compiler_cxx')
	
def configure(conf):
	conf.check_tool('compiler_cxx')
	conf.check_tool('node_addon')

def build(bld):
	cargo = bld.new_task_gen('cxx', 'shlib', 'node_addon')
	cargo.cxxflags = ["-g",]
	cargo.target = 'nTPL.native'
	cargo.source = 'nTPL.native.cc'